Added Issue and PR template
commclassroom/commclassroomBackend pull request #15
Opened 2021-09-08 06:48 UTC by ShaileshKumar007

This PR fixes #7

2021-09-08 07:30 UTC, YashKumarVerma requested changes

2021-09-08 07:30 UTC, YashKumarVerma commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        Device - [e.g. iPhone6]
renew device to "system"
rename iPhone to a laptop / pc specific detail as the backend would run on a PC and not a mobile

2021-09-08 07:30 UTC, YashKumarVerma commented on .github/workflows/tests.yml
> +    steps:
this file is not needed

2021-09-08 15:26 UTC, YashKumarVerma requested changes

2021-09-08 15:26 UTC, YashKumarVerma commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        Version [e.g. 10]
its the backend, we really do not worry about the laptop or browser.
Something like NodeJS Version, NPM version would be appreciated.

2021-09-09 04:40 UTC, ShaileshKumar007 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        Version [e.g. 10]
I've changed the description. Let me know if any further changes are required.

2021-09-09 06:00 UTC, YashKumarVerma approved these changes

2021-09-09 06:00 UTC, YashKumarVerma commented
just remove the GitHub actions workflow file then we can merge this.

2021-09-09 10:04 UTC, ShaileshKumar007 commented
> just remove the GitHub actions workflow file then we can merge this.

I've made a PR related to this (Deleted GitHub actions workflow folder).

2021-09-09 10:55 UTC, divyanshu-parihar approved these changes

2021-09-10 05:41 UTC, ShaileshKumar007 commented
> just remove the GitHub actions workflow file then we can merge this.

Done. Plz review it and let me know if any further changes required

2021-09-12 13:03 UTC, YashKumarVerma approved these changes

2021-09-12 13:03 UTC, merged

2021-09-12 13:04 UTC, YashKumarVerma commented
thanks !