ESLint script at `npm run lint`
commclassroom/commclassroomBackend pull request #20
Opened 2021-09-08 08:31 UTC by Saatvik-droid

For Issue #17

2021-09-08 15:38 UTC, YashKumarVerma requested changes

2021-09-08 15:38 UTC, YashKumarVerma commented on package.json
> +    "eslint-config-google": "^0.14.0",
not needed, we are using airbnb style

2021-09-08 16:46 UTC, Saatvik-droid commented on package.json
> +    "eslint-config-google": "^0.14.0",
That should be fixed now

2021-09-08 16:53 UTC, Saatvik-droid commented
I have no idea what these package-lock.json and package.json conflicts have come from

2021-09-09 03:13 UTC, divyanshu-parihar commented
@Saatvik-droid  what happened after doing "git pull"?

2021-09-09 03:19 UTC, Saatvik-droid commented
> 
> 
> @Saatvik-droid what happened after doing "git pull"?

Do you want me to run `git pull`? I have just cloned the repo, run npm i and pushed my changes.

2021-09-09 03:23 UTC, closed without merging

2021-09-09 03:40 UTC, YashKumarVerma commented
Hey there, conflicts come when your copy of the repository is outdated from what we have on server. To fix this,  you need to pull the changes and then resolve the merge conflicts.

2021-09-09 05:11 UTC, Saatvik-droid commented
I know that, but when I try to install these new deps the lock file changes to use you use version 2 #23 and therefore the conflicts