Updated the README.md
commclassroom/commclassroomBackend pull request #21
Opened 2021-09-08 09:07 UTC by ShaileshKumar007

This PR fixes #6

2021-09-08 15:36 UTC, YashKumarVerma requested changes

2021-09-08 15:36 UTC, YashKumarVerma commented on README.md
> +For development, you will only need Node.js and a node global package, Yarn, installed in your environement.
yarn is not required for the project. works fine with npm.

2021-09-08 15:36 UTC, YashKumarVerma commented on README.md
> +
add project specific instructions, people do not need to clone the project to run it.
use this repo's URL itself.

2021-09-08 15:36 UTC, YashKumarVerma commented on README.md
> +    $ yarn build
use NPM specific commands.
yarn can be added, but don't leave npm

2021-09-08 15:36 UTC, YashKumarVerma commented on README.md
> +  You can install nodejs and npm easily with apt install, just run the following commands.
not needed, if you want, can add a link to a blog that installs nodejs

2021-09-09 05:58 UTC, YashKumarVerma requested changes

2021-09-09 05:58 UTC, YashKumarVerma commented on README.md
> +    npm run build
this is used in typescript projects or projects with build systems. We do not need this line.

2021-09-09 10:06 UTC, ShaileshKumar007 commented on README.md
> +    npm run build
Actually, I'm new to this, so can you guide me little bit like what should I do.

2021-09-09 11:01 UTC, divyanshu-parihar commented on README.md
> +    npm run build
Actually what he is saying is , in typescript we compile TS to js for production , but this project is already in js so there is not need to of any type of build command atleast at this point unless team decide to use webpack or something . So you can just remove that line.

2021-09-09 11:03 UTC, divyanshu-parihar commented on README.md
> +    npm run build
> Actually what he is saying is , in typescript we compile TS to js for production , but this project is already in js so there is not need to of any type of build command atleast at this point unless team decide to use webpack or something . So you can just remove that line.

Actually what he is saying is , in typescript we compile TS to js for production , but this project is already in js so there is not need to of any type of build command atleast at this point unless team decide to use webpack or something . So you can just remove that line.

2021-09-10 05:43 UTC, ShaileshKumar007 commented on README.md
> +    npm run build
oh ok, got it now. Thank you @divyanshu-parihar for helping me

2021-09-10 05:48 UTC, ShaileshKumar007 commented on README.md
> +    npm run build
> this is used in typescript projects or projects with build systems. We do not need this line.

Build command deleted.

2021-09-12 13:05 UTC, merged

2021-09-12 13:06 UTC, YashKumarVerma commented
thanks !