Added Course schema and CRUD APIs on Course #30
commclassroom/commclassroomBackend pull request #32
Opened 2021-09-13 06:16 UTC by Mohit-Swain

Things I did in this PR:
- created a mongoose schema of course
- API to get a course by id
- API to create a new course
- API to update a course
- API to delete a course

resolves #30

2021-09-14 14:37 UTC, SoulNinja-dev approved these changes
Yes looks good to me.

2021-09-14 14:38 UTC, SoulNinja-dev commented
@YashKumarVerma can you also review and then merge it 👍

2021-09-14 14:53 UTC, YashKumarVerma requested changes

2021-09-14 14:53 UTC, YashKumarVerma commented on src/modules/course/course.controller.js
> +    let { title, instructors, enrollments, featured, tags, playlistId } = obj;
can we use const here in place of let? are these values being changed anywhere?

2021-09-14 14:53 UTC, YashKumarVerma commented on src/modules/course/course.controller.js
> +      );
passing an object is better than passing so many params

2021-09-14 14:53 UTC, YashKumarVerma commented on src/modules/course/course.controller.js
> +        playlistId,
pass an object in place of so many params, then we do not need to care about their order and default values

2021-09-14 14:53 UTC, YashKumarVerma commented on src/modules/course/course.controller.js
> +    logger.info('[course]: Get course no. ' + id);
prefer lowercase in logs

2021-09-14 14:53 UTC, YashKumarVerma commented on src/modules/course/course.service.js
> +    if (!course) {
better to use comparisons with null or undefined in place of `!variable`

2021-09-14 14:53 UTC, YashKumarVerma commented on src/modules/course/course.service.js
> +    playlistId,
changing this to an object will reduce the number of params

2021-09-15 09:22 UTC, Mohit-Swain commented
@YashKumarVerma I have made the requested changes, please have a look at it.

2021-09-15 09:34 UTC, YashKumarVerma requested changes

2021-09-15 09:34 UTC, YashKumarVerma commented on src/modules/course/course.controller.js
> +    logger.info('[course]: Get course no. ' + id);
?

2021-09-15 09:34 UTC, YashKumarVerma commented on src/modules/course/course.service.js
> +    if (!course) {
??

2021-09-15 09:34 UTC, YashKumarVerma commented on src/modules/course/course.controller.js
> +    }
the logging line should be inside the try block, after calling the service. currently it runs regardless whether the operation was successful or not

2021-09-16 05:21 UTC, Mohit-Swain commented
@YashKumarVerma I made the changes.

2021-09-16 10:55 UTC, YashKumarVerma requested changes

2021-09-16 10:55 UTC, YashKumarVerma commented on src/modules/course/course.service.js
> +    const course_rating = this.getAvgRating(courseObj.enrollments);
use camilCase only

2021-09-16 10:55 UTC, YashKumarVerma commented on src/modules/course/course.service.js
> +      course_rating,
camelCase

2021-09-16 10:55 UTC, YashKumarVerma commented on src/modules/course/course.service.js
> +        course_rating,
case

2021-09-16 10:55 UTC, YashKumarVerma commented on src/modules/course/course.service.js
> +  }
what would be the usecase when we'd need to fetch only the rating count? Would it not be better if we get the rating along with other course details?

2021-09-16 11:24 UTC, Mohit-Swain commented on src/modules/course/course.service.js
> +  }
It is a util function that will calculate the avg rating of all the enrolled students and then store it in the database. It doesn't get called by the controller, but it gets called by the Create course and update course functions to calculate the avg rating.

2021-09-20 04:53 UTC, YashKumarVerma commented
kindly checkout : https://github.com/commclassroom/commclassroomBackend/issues/38

2021-09-27 04:19 UTC, YashKumarVerma commented
any updates?

2021-09-27 07:32 UTC, Mohit-Swain commented
Sorry, I was busy in the prev week. I am starting to continue from today

2021-09-27 09:12 UTC, Mohit-Swain commented
@YashKumarVerma can you check the commits.

2021-09-27 15:53 UTC, YashKumarVerma approved these changes

2021-09-27 15:53 UTC, merged

2021-09-27 15:53 UTC, YashKumarVerma commented
thanks !