search by email / search by id : service functions
commclassroom/commclassroomBackend pull request #36
Opened 2021-09-15 03:51 UTC by divyanshu-parihar

changed some schema and add 2 service functions to user.service to search user by email and id

2021-09-15 04:25 UTC, divyanshu-parihar commented
This pr is to add some features mentioned in #14

2021-09-15 09:36 UTC, YashKumarVerma requested changes

2021-09-15 09:36 UTC, YashKumarVerma commented on tests/app.test.js
>      expect(response.body.alive).toEqual(true);
why this?

2021-09-15 09:36 UTC, YashKumarVerma commented on src/modules/user/user.service.js
> +    return user ? { notFound: false, ...user } : null;
services are expected to return datata, why returning things like notFound : true / false?

If the return is null or undefined, the caller function can see its not found. Any particular reason for doing this way?

2021-09-15 13:49 UTC, divyanshu-parihar commented on tests/app.test.js
>      expect(response.body.alive).toEqual(true);
Thought it will be better, as this not testing for registering a user .
should i change it or not?

2021-09-15 13:50 UTC, divyanshu-parihar commented on src/modules/user/user.service.js
> +    return user ? { notFound: false, ...user } : null;
Okay, I'll change that .

2021-09-16 06:50 UTC, divyanshu-parihar commented
@YashKumarVerma  made some changes ,

2021-09-16 10:55 UTC, YashKumarVerma commented on tests/app.test.js
>      expect(response.body.alive).toEqual(true);
but this does not actually test the registration right? then what's the use.

2021-09-16 10:57 UTC, YashKumarVerma approved these changes

2021-09-16 10:57 UTC, YashKumarVerma commented on src/modules/user/user.service.js
> +    const user = await User.find({ email: userEmail });
could have used object shorthand like `.find({email})`, but OK

2021-09-16 10:58 UTC, merged

2021-09-16 10:58 UTC, YashKumarVerma commented
thanks !

2021-09-16 16:03 UTC, divyanshu-parihar commented
Nvm